---
title: Een bestand lezen met Python
hero_image: images/banner.png
description: generic-python-file-read description
version: 4
listed: false
ingredient: true
copyedit: false
last_tested: "2021-10-07"
steps:
  - title: Een bestand lezen met Python
