title: generic-python-file-read
hero_image: images/banner.png
description: generic-python-file-read description
version: 4
listed: false
copyedit: false
last_tested: "2021-10-07"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
